package com.example.ustudybuddyv1.Activity;

import android.os.Bundle;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.ustudybuddyv1.R;
import com.example.ustudybuddyv1.Model.StudyGroup;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Objects;

public class StudyGroupCRUDActivity extends AppCompatActivity {

    private EditText editGroupName, editLocation;
    private Button btnSaveGroup;
    private DatabaseReference studyGroupRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_study_group);

        // Firebase initialization
        studyGroupRef = FirebaseDatabase.getInstance().getReference("study_groups");

        // UI components
        editGroupName = findViewById(R.id.edit_group_name);
        editLocation = findViewById(R.id.edit_location);
        btnSaveGroup = findViewById(R.id.btn_create_group);

        // Save group setup
        btnSaveGroup.setOnClickListener(v -> saveStudyGroup());
    }

    // Save study group data
    private void saveStudyGroup() {
        String groupName = editGroupName.getText().toString().trim();
        String location = editLocation.getText().toString().trim();

        // Validate inputs
        if (groupName.isEmpty() || location.isEmpty()) {
            Toast.makeText(this, "Please fill in all fields", Toast.LENGTH_SHORT).show();
            return;
        }

        // Create a new group and set data
        String groupId = studyGroupRef.push().getKey();
        if (groupId != null) {
            // Get current user ID for the creator
            String creatorId = Objects.requireNonNull(FirebaseAuth.getInstance().getCurrentUser()).getUid();

            // Create a new StudyGroup object with all necessary information
            StudyGroup newGroup = new StudyGroup(
                    groupId,          // groupId generated by Firebase
                    groupName,        // group name
                    creatorId,        // creator ID (current user's ID)
                    location,         // location
                    null,             // members list will be initialized as null or empty
                    0,                // initial members count is 0
                    true,             // public status (set to true or change as needed)
                    ""                // subject (if needed, otherwise leave it empty)
            );

            // Save to Firebase
            studyGroupRef.child(groupId).setValue(newGroup)
                    .addOnSuccessListener(aVoid -> {
                        Toast.makeText(this, "Group created successfully!", Toast.LENGTH_SHORT).show();
                        setResult(RESULT_OK);  // Notify the previous activity/fragment
                        finish();  // Close the activity
                    })
                    .addOnFailureListener(e -> {
                        Toast.makeText(this, "Failed to create group", Toast.LENGTH_SHORT).show();
                    });
        } else {
            Toast.makeText(this, "Error generating group ID", Toast.LENGTH_SHORT).show();
        }
    }
}
